### ISSUE TITLE
Inquiry about Python Environment and Library Versions

### ISSUE THREAD

**Issue by zhengzhi-1997** [RUC-GSAI/YuLan-Rec#1]
I've encountered some issues that might be related to version mismatches of the dependencies, would it be possible for you to provide more details about:

1. The exact version of Python you're using.
2. The specific versions of each library in the requirements.txt file.

Having this information will greatly assist in ensuring that the project runs as expected in a replicated environment.

**Comment by Paitesanshi** [comment]
@zhengzhi-1997 Hello,
Thank you for reaching out. To address your inquiry:
The Python version we are using in this project is **3.11.3**.
Regarding the specific versions of each library in the `requirements.txt `file, we have updated the repository with the `requirements.txt` containing exact version numbers. You can check it directly in the repository to ensure consistent environment replication.
If you face any issues setting up or running the project, please don't hesitate to let us know. We're here to help.

**Comment by Paitesanshi** [comment]
Done

**Comment by ummagumm-a** [comment]
Hi. You wrote that you use python==3.11.3, but trying to install `faiss` with command `conda install faiss-cpu -c pytorch` (from the README) gives me an error:

```
Found conflicts! Looking for incompatible packages.
This can take several minutes.  Press CTRL-C to abort.
failed                                                                          

UnsatisfiableError: The following specifications were found
to be incompatible with the existing python installation in your environment:

Specifications:

  - faiss-cpu -> python[version='>=2.7,<2.8.0a0|>=3.10,<3.11.0a0|>=3.9,<3.10.0a0|>=3.8,<3.9.0a0|>=3.7,<3.8.0a0|>=3.6,<3.7.0a0|>=3.5,<3.6.0a0']

Your python: python==3.11.3

If python is on the left-most side of the chain, that's the version you've asked for.
When python appears to the right, that indicates that the thing on the left is somehow
not available for the python version you are constrained to. Note that conda will not
change your python version to a different minor version unless you explicitly specify
that.
```

Can you please recheck which python version is required to successfully install all requirements? 
Best regards!
