### ISSUE TITLE
请问如何指定本地部署的LLM？

### ISSUE THREAD

**Issue by Barry1915** [RUC-GSAI/YuLan-Rec#10]
我看config文件里面只能用chatgpt的key来执行，有指定本地模型路径，调用本地LLM的地方吗

**Comment by Paitesanshi** [comment]
嗨，感谢对RecAgent的关注！
很遗憾暂时没有直接调用本地LLM的接口。不过RecAgent使用LangChain框架，可以参考LangChain调用本地LLM的方式添加本地部署的接口。
