### ISSUE TITLE
AttributeError: module 'utils.utils' has no attribute 'get_entropy'

### ISSUE THREAD

**Issue by Minami-su** [RUC-GSAI/YuLan-Rec#11]
File "/home/YuLan-Rec-main/simulator.py", line 551, in one_step
    entropy = utils.get_entropy(ids, self.data)
AttributeError: module 'utils.utils' has no attribute 'get_entropy'

**Comment by Paitesanshi** [comment]
Thank you very much for bringing this to our attention! The issue has been addressed and the necessary changes have been made. Please feel free to reach out if you have any further questions or suggestions. Thank you for your support and understanding.
