### ISSUE TITLE
ModuleNotFoundError: No module named 'langchain.experimental'

### ISSUE THREAD

**Issue by sudusuperman** [RUC-GSAI/YuLan-Rec#2]
Hi,

I tried to deploy with python 3.8 or 3.9 in conda, both has error "ModuleNotFoundError: No module named 'langchain.experimental'"

Searched online, the solution seems to be re-install langchain with version <=0.0.187. But this does not satisfy the "langchain==0.0.260" in requirement.txt

Could you please verify this issue? Thx

**Comment by Paitesanshi** [comment]
@sudusuperman I apologize for the inconvenience. You are right, there was an issue when exporting the requirements. We have now updated the langchain version in the requirements to 0.0.187. Please try deploying again with this version. Thank you again for pointing this out. If you have any other questions, please let us know.

**Comment by sudusuperman** [comment]
Thx for the fast response!
0.0.187 works, Thx!

**Comment by sudusuperman** [comment]
By the way, here are 2 more suggestions about requirements.
1. could you please also specify the python version? I tried 3.7~3.9, and only 3.9 works.
2. about faiss in requirement.txt, maybe you can just use faiss-cpu==1.7.2. this works for me.
Thx!
