### ISSUE TITLE
Pretrained embedding data not found

### ISSUE THREAD

**Issue by nicksukie** [RUC-GSAI/YuLan-Rec#20]
Hi,

I am trying to use RecAgent on my own dataset. I am not sure what to input for `model_name` under `get_embedding_model()` in utils.py.

With the current model as `/data/pretrain_dir/all-mpnet-base-v2"`, I am receiving the error `ValueError: Path /data/pretrain_dir/all-mpnet-base-v2 not found`.

Thanks for your assistance.

Regards.

**Comment by Paitesanshi** [comment]
@nicksukie Hi,

You can replace the model path with `sentence-transformers/all-mpnet-base-v2`. This should resolve the issue. Let me know if you need further assistance!

Regards.
