### ISSUE TITLE
How to run the demo in the video?

### ISSUE THREAD

**Issue by LIUQI-creat** [RUC-GSAI/YuLan-Rec#6]
Hi，
Thanks for your outstanding work! I am reproducing the demo and the command I am executing is `python -u run_demo.py --config_file config/config.yaml --output_file messages.json --log_file simulation.log`. 
However, the demo shows very little functionality, the figure is 
<img width="960" alt="973d9f016a973f2fecb1f71f139fba4" src="https://github.com/RUC-GSAI/YuLan-Rec/assets/75316518/bb7b84d6-40f5-4885-9733-8754cd3e8de7">

But the interface in the demo video looks like this：
<img width="861" alt="119fb011c23998f6c9c1674d92f8a3c" src="https://github.com/RUC-GSAI/YuLan-Rec/assets/75316518/156d0f24-6abf-4584-b1f6-89a0bf42a032">

How to run the functionality of the demo in the video, such as system-level and agent-level interventions, the ability to change agent configurations, the ability to display social relationships, the ability to play roles?

Hope you reply!

**Comment by Paitesanshi** [comment]
@LIUQI-creat Hi, thank you for your interest in our work! The new version of the front-end code will be made public after the paper is accepted. For now, you can achieve intervention and role-playing functionalities through the command line. To enable intervention at the beginning of each round, uncomment line 1210 in `simulator.py`. To enable role-playing, add the command line parameter `--play_role=True` and replace `asyncio.run` in `agents/roleagent.py` with `input`.

**Comment by LIUQI-creat** [comment]
> @LIUQI-creat Hi, thank you for your interest in our work! The new version of the front-end code will be made public after the paper is accepted. For now, you can achieve intervention and role-playing functionalities through the command line. To enable intervention at the beginning of each round, uncomment line 1210 in `simulator.py`. To enable role-playing, add the command line parameter `--play_role=True` and replace `asyncio.run` in `agents/roleagent.py` with `input`.

Thank you for your patient reply! I sincerely wish your paper will be successfully accepted！

**Comment by Paitesanshi** [comment]
Thx for your kind words!
