### ISSUE TITLE
。真人可以采取与其他特工相同的操作，例如观看推荐的电影、与其他特工聊天或公开发帖。这部分实现的代码在哪里怎么实现的呢

### ISSUE THREAD

**Issue by 2642543078** [RUC-GSAI/YuLan-Rec#7]

**Comment by Paitesanshi** [comment]
@2642543078 Hi， 感谢对RecAgent的关注！
真人扮演部分的实现请主要参考`agents/roleagent.py`
https://github.com/RUC-GSAI/YuLan-Rec/blob/5578547b46e94ce0589239085a0540cede9578fc/agents/roleagent.py#L27
其中定义了所有的真人扮演Agent的行为。
创建真人Agent请参考https://github.com/RUC-GSAI/YuLan-Rec/blob/5578547b46e94ce0589239085a0540cede9578fc/simulator.py#L894
