### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused'))

### ISSUE THREAD

**Issue by Barry1915** [RUC-GSAI/YuLan-Rec#9]
openai.error.APIConnectionError: Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/engines/text-embedding-ada-002/embeddings (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f36b7fc1ff0>: Failed to establish a new connection: [Errno 111] Connection refused'))

**Comment by Barry1915** [comment]
这个应该是我部署在服务器上，服务器没梯子的原因

**Comment by Paitesanshi** [comment]
好的，如果没有问题，将关闭这条issue。
